import { User, Project, Task, ActivityEvent, NotificationItem } from './types';

export const currentUser: User = {
  id: 'usr-1',
  name: 'Carlos Martínez',
  email: 'carlos.martinez@nexora.io',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  role: 'Product Lead & Director',
  department: 'Producto & Operaciones',
  status: 'disponible',
  activeProjectsCount: 6,
  pendingTasksCount: 12,
};

export const mockUsers: User[] = [
  currentUser,
  {
    id: 'usr-2',
    name: 'Laura Gómez',
    email: 'laura.gomez@nexora.io',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=256',
    role: 'Senior Frontend Engineer',
    department: 'Tecnología',
    status: 'disponible',
    activeProjectsCount: 4,
    pendingTasksCount: 9,
  },
  {
    id: 'usr-3',
    name: 'Andrés Silva',
    email: 'andres.silva@nexora.io',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256',
    role: 'DevOps & Cloud Architect',
    department: 'Infraestructura',
    status: 'ocupado',
    activeProjectsCount: 5,
    pendingTasksCount: 16,
  },
  {
    id: 'usr-4',
    name: 'María Torres',
    email: 'maria.torres@nexora.io',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=256',
    role: 'Senior Product Designer',
    department: 'Diseño UX/UI',
    status: 'disponible',
    activeProjectsCount: 3,
    pendingTasksCount: 7,
  },
  {
    id: 'usr-5',
    name: 'Javier Méndez',
    email: 'javier.mendez@nexora.io',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256',
    role: 'Lead Backend Engineer',
    department: 'Tecnología',
    status: 'ocupado',
    activeProjectsCount: 4,
    pendingTasksCount: 14,
  },
  {
    id: 'usr-6',
    name: 'Elena Rojas',
    email: 'elena.rojas@nexora.io',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=256',
    role: 'QA Automation Lead',
    department: 'Calidad & Pruebas',
    status: 'disponible',
    activeProjectsCount: 5,
    pendingTasksCount: 11,
  },
  {
    id: 'usr-7',
    name: 'Diego Morales',
    email: 'diego.morales@nexora.io',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=256',
    role: 'Security & Compliance Officer',
    department: 'Ciberseguridad',
    status: 'ausente',
    activeProjectsCount: 2,
    pendingTasksCount: 5,
  },
];

export const initialProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Rediseño Portal Corporativo',
    description: 'Renovación completa de la experiencia digital corporativa para clientes enterprise, con nuevo sistema de diseño y portal de autoservicio.',
    clientOrArea: 'Marketing & Comercial',
    manager: currentUser,
    team: [currentUser, mockUsers[1], mockUsers[3], mockUsers[4]],
    progress: 72,
    priority: 'alta',
    startDate: '2026-08-01',
    dueDate: '2026-09-18',
    status: 'activo',
    createdAt: '2026-08-01T10:00:00Z',
    milestones: [
      { id: 'm-1', title: 'Aprobación de Wireframes & Design System', date: '2026-08-15', completed: true },
      { id: 'm-2', title: 'Implementación Frontend de Componentes Core', date: '2026-09-05', completed: true },
      { id: 'm-3', title: 'Integración CMS y Portal de Clientes', date: '2026-09-12', completed: false },
      { id: 'm-4', title: 'Lanzamiento Oficial & Pruebas de Carga', date: '2026-09-18', completed: false },
    ],
  },
  {
    id: 'proj-2',
    name: 'Migración de infraestructura',
    description: 'Transición hacia microservicios en Kubernetes multi-región con observabilidad Datadog y política Zero-Trust.',
    clientOrArea: 'Tecnología & Cloud',
    manager: mockUsers[2],
    team: [mockUsers[2], mockUsers[4], mockUsers[6]],
    progress: 48,
    priority: 'media',
    startDate: '2026-07-15',
    dueDate: '2026-09-24',
    status: 'activo',
    createdAt: '2026-07-15T09:00:00Z',
    milestones: [
      { id: 'm-5', title: 'Aprovisionamiento de Clusters EKS', date: '2026-08-10', completed: true },
      { id: 'm-6', title: 'Migración de Bases de Datos PostgreSQL', date: '2026-09-10', completed: false },
      { id: 'm-7', title: 'Cutover de Tráfico DNS y Monitoreo', date: '2026-09-24', completed: false },
    ],
  },
  {
    id: 'proj-3',
    name: 'Nueva plataforma comercial',
    description: 'Suite de cotizaciones dinámicas y checkout B2B con pasarela de pagos integrada para mercados internacionales.',
    clientOrArea: 'Comercial & Ventas',
    manager: currentUser,
    team: [currentUser, mockUsers[1], mockUsers[4], mockUsers[5]],
    progress: 91,
    priority: 'alta',
    startDate: '2026-06-01',
    dueDate: '2026-09-08',
    status: 'activo',
    createdAt: '2026-06-01T08:30:00Z',
    milestones: [
      { id: 'm-8', title: 'Integración API Pagos Stripe & Adyen', date: '2026-08-01', completed: true },
      { id: 'm-9', title: 'Testing E2E de Flujo Checkout', date: '2026-08-25', completed: true },
      { id: 'm-10', title: 'Despliegue a Producción Beta', date: '2026-09-08', completed: false },
    ],
  },
  {
    id: 'proj-4',
    name: 'App Móvil Clientes v2',
    description: 'Rediseño de la aplicación móvil nativa con autenticación biométrica y modo offline sincronizado.',
    clientOrArea: 'Producto',
    manager: mockUsers[1],
    team: [mockUsers[1], mockUsers[3], mockUsers[5]],
    progress: 35,
    priority: 'critica',
    startDate: '2026-08-10',
    dueDate: '2026-10-15',
    status: 'activo',
    createdAt: '2026-08-10T14:00:00Z',
    milestones: [
      { id: 'm-11', title: 'Diseño UX en Figma y Prototipos', date: '2026-08-30', completed: true },
      { id: 'm-12', title: 'Arquitectura Offline-First', date: '2026-09-20', completed: false },
      { id: 'm-13', title: 'Publicación TestFlight y Google Play Beta', date: '2026-10-15', completed: false },
    ],
  },
  {
    id: 'proj-5',
    name: 'Sistema de Facturación Electrónica',
    description: 'Módulo fiscal automatizado para emisión de comprobantes en tiempo real con validación gubernamental.',
    clientOrArea: 'Finanzas & Legal',
    manager: mockUsers[4],
    team: [mockUsers[4], mockUsers[5], currentUser],
    progress: 60,
    priority: 'media',
    startDate: '2026-07-01',
    dueDate: '2026-09-30',
    status: 'en_pausa',
    createdAt: '2026-07-01T11:00:00Z',
    milestones: [
      { id: 'm-14', title: 'Conexión con Servicio de Rentas', date: '2026-08-05', completed: true },
      { id: 'm-15', title: 'Pruebas de Certificados Digitales', date: '2026-09-15', completed: false },
    ],
  },
  {
    id: 'proj-6',
    name: 'Auditoría de Seguridad SOC2',
    description: 'Revisión y acreditación de controles de seguridad de la información, encriptación y trazabilidad de accesos.',
    clientOrArea: 'Operaciones & Compliance',
    manager: mockUsers[6],
    team: [mockUsers[6], mockUsers[2], currentUser],
    progress: 15,
    priority: 'alta',
    startDate: '2026-09-01',
    dueDate: '2026-11-12',
    status: 'planificacion',
    createdAt: '2026-09-01T09:00:00Z',
    milestones: [
      { id: 'm-16', title: 'Mapeo de Políticas de Acceso', date: '2026-09-25', completed: false },
      { id: 'm-17', title: 'Auditoría Externa de Penetración', date: '2026-10-20', completed: false },
      { id: 'm-18', title: 'Certificación Final Type II', date: '2026-11-12', completed: false },
    ],
  },
];

export const initialTasks: Task[] = [
  {
    id: 'tsk-1',
    projectId: 'proj-1',
    projectName: 'Rediseño Portal Corporativo',
    title: 'Finalizar paleta de tokens y componentes en Figma',
    description: 'Consolidar variables de color semánticas, espaciados y exportar catálogo de iconos SVG para el equipo frontend.',
    assignee: mockUsers[3],
    priority: 'alta',
    status: 'completada',
    dueDate: '2026-09-03',
    completed: true,
    subtasks: [
      { id: 'sub-1', title: 'Definir tokens de dark mode', completed: true },
      { id: 'sub-2', title: 'Revisión de contraste WCAG AAA', completed: true },
    ],
    comments: [
      {
        id: 'c-1',
        taskId: 'tsk-1',
        author: mockUsers[3],
        content: 'Tokens exportados y sincronizados con el repositorio de diseño.',
        createdAt: '2026-09-02T10:15:00Z',
      },
    ],
    createdAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'tsk-2',
    projectId: 'proj-1',
    projectName: 'Rediseño Portal Corporativo',
    title: 'Implementar Command Palette con atajos de teclado',
    description: 'Construir el modal accesible con escucha global en ⌘K y Ctrl+K, con soporte para filtrado en tiempo real.',
    assignee: currentUser,
    priority: 'alta',
    status: 'en_progreso',
    dueDate: '2026-09-05',
    completed: false,
    subtasks: [
      { id: 'sub-3', title: 'Listener global de teclas', completed: true },
      { id: 'sub-4', title: 'Agrupación de resultados', completed: true },
      { id: 'sub-5', title: 'Navegación con flechas y foco accesible', completed: false },
    ],
    comments: [
      {
        id: 'c-2',
        taskId: 'tsk-2',
        author: currentUser,
        content: 'Trabajando en el manejo de teclado para accesibilidad.',
        createdAt: '2026-09-02T12:30:00Z',
      },
    ],
    createdAt: '2026-08-30T11:00:00Z',
  },
  {
    id: 'tsk-3',
    projectId: 'proj-2',
    projectName: 'Migración de infraestructura',
    title: 'Configurar réplicas y failover automático en PostgreSQL',
    description: 'Asegurar RPO menor a 1 minuto y RTO menor a 5 minutos ante cortes en la zona de disponibilidad primaria.',
    assignee: mockUsers[2],
    priority: 'critica',
    status: 'pendiente',
    dueDate: '2026-09-08',
    completed: false,
    subtasks: [
      { id: 'sub-6', title: 'Crear réplica de lectura en us-east-2', completed: false },
      { id: 'sub-7', title: 'Test de degradación de red', completed: false },
    ],
    comments: [],
    createdAt: '2026-08-25T14:00:00Z',
  },
  {
    id: 'tsk-4',
    projectId: 'proj-3',
    projectName: 'Nueva plataforma comercial',
    title: 'Validación de webhook de transacciones bancarias',
    description: 'Implementar firma criptográfica HMAC-SHA256 para verificar la autenticidad de los eventos recibidos.',
    assignee: mockUsers[4],
    priority: 'alta',
    status: 'en_revision',
    dueDate: '2026-09-04',
    completed: false,
    subtasks: [
      { id: 'sub-8', title: 'Pruebas de idempotencia en pagos repetidos', completed: true },
      { id: 'sub-9', title: 'Configurar colas SQS para reintentos con backoff', completed: true },
    ],
    comments: [
      {
        id: 'c-3',
        taskId: 'tsk-4',
        author: mockUsers[4],
        content: 'Código listo para code review de Elena.',
        createdAt: '2026-09-02T11:00:00Z',
      },
    ],
    createdAt: '2026-08-29T10:00:00Z',
  },
  {
    id: 'tsk-5',
    projectId: 'proj-1',
    projectName: 'Rediseño Portal Corporativo',
    title: 'Revisión de rendimiento Lighthouse y Core Web Vitals',
    description: 'Garantizar puntaje superior a 95 en Desktop y Mobile, optimizando fuentes e imágenes WebP.',
    assignee: currentUser,
    priority: 'media',
    status: 'pendiente',
    dueDate: '2026-09-10',
    completed: false,
    subtasks: [],
    comments: [],
    createdAt: '2026-08-31T09:00:00Z',
  },
  {
    id: 'tsk-6',
    projectId: 'proj-4',
    projectName: 'App Móvil Clientes v2',
    title: 'Integrar autenticación biométrica (FaceID / TouchID)',
    description: 'Almacenamiento seguro de tokens JWT en Keychain de iOS y Android Keystore.',
    assignee: mockUsers[1],
    priority: 'alta',
    status: 'en_progreso',
    dueDate: '2026-09-14',
    completed: false,
    subtasks: [
      { id: 'sub-10', title: 'Flujo de enrolamiento biométrico', completed: true },
      { id: 'sub-11', title: 'Fallback a PIN numérico', completed: false },
    ],
    comments: [],
    createdAt: '2026-09-01T15:00:00Z',
  },
  {
    id: 'tsk-7',
    projectId: 'proj-6',
    projectName: 'Auditoría de Seguridad SOC2',
    title: 'Habilitar rotación de credenciales IAM de 60 días',
    description: 'Automatizar con Terraform y AWS Secrets Manager la expiración de llaves programáticas.',
    assignee: mockUsers[6],
    priority: 'critica',
    status: 'pendiente',
    dueDate: '2026-09-12',
    completed: false,
    subtasks: [],
    comments: [],
    createdAt: '2026-09-01T16:00:00Z',
  },
  {
    id: 'tsk-8',
    projectId: 'proj-3',
    projectName: 'Nueva plataforma comercial',
    title: 'Pruebas de carga con 10,000 usuarios concurrentes en checkout',
    description: 'Simular picos de Black Friday con k6 y monitorear consumo de memoria en pods.',
    assignee: mockUsers[5],
    priority: 'alta',
    status: 'completada',
    dueDate: '2026-09-01',
    completed: true,
    subtasks: [
      { id: 'sub-12', title: 'Crear scripts de k6 con escenarios de compra', completed: true },
      { id: 'sub-13', title: 'Verificar latencia p99 menor a 300ms', completed: true },
    ],
    comments: [
      {
        id: 'c-4',
        taskId: 'tsk-8',
        author: mockUsers[5],
        content: 'Latencia p99 registrada en 184ms. Informe adjunto en Datadog.',
        createdAt: '2026-09-01T18:00:00Z',
      },
    ],
    createdAt: '2026-08-20T10:00:00Z',
  },
];

export const initialActivities: ActivityEvent[] = [
  {
    id: 'act-1',
    user: currentUser,
    action: 'actualizó el proyecto',
    entity: 'Portal Corporativo',
    entityType: 'project',
    timestamp: '2026-09-02T13:45:00Z',
    timeAgo: 'Hace 30 min',
    projectId: 'proj-1',
  },
  {
    id: 'act-2',
    user: mockUsers[1],
    action: 'completó la tarea',
    entity: 'Revisión de arquitectura',
    entityType: 'task',
    timestamp: '2026-09-02T12:15:00Z',
    timeAgo: 'Hace 2 horas',
    projectId: 'proj-1',
  },
  {
    id: 'act-3',
    user: mockUsers[2],
    action: 'fue asignado a',
    entity: 'Migración de API Gateway',
    entityType: 'task',
    timestamp: '2026-09-02T10:20:00Z',
    timeAgo: 'Hace 4 horas',
    projectId: 'proj-2',
  },
  {
    id: 'act-4',
    user: mockUsers[3],
    action: 'cambió la prioridad a Alta en',
    entity: 'Landing comercial',
    entityType: 'project',
    timestamp: '2026-09-01T17:30:00Z',
    timeAgo: 'Ayer a las 17:30',
    projectId: 'proj-3',
  },
  {
    id: 'act-5',
    user: currentUser,
    action: 'creó un nuevo hito en',
    entity: 'Auditoría de Seguridad SOC2',
    entityType: 'project',
    timestamp: '2026-09-01T14:10:00Z',
    timeAgo: 'Ayer a las 14:10',
    projectId: 'proj-6',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Nueva tarea asignada',
    description: 'Laura Gómez te asignó la tarea "Implementar Command Palette".',
    timeAgo: 'Hace 15 min',
    read: false,
    type: 'assignment',
  },
  {
    id: 'notif-2',
    title: 'Fecha límite próxima',
    description: 'El proyecto "Portal Corporativo" vence en 3 días.',
    timeAgo: 'Hace 2 horas',
    read: false,
    type: 'deadline',
  },
  {
    id: 'notif-3',
    title: 'Tarea completada',
    description: 'Elena Rojas marcó "Pruebas de carga en checkout" como completada.',
    timeAgo: 'Hace 5 horas',
    read: true,
    type: 'completion',
  },
  {
    id: 'notif-4',
    title: 'Mención en comentario',
    description: 'Andrés Silva te mencionó en el proyecto "Migración de infraestructura".',
    timeAgo: 'Ayer',
    read: true,
    type: 'mention',
  },
];
